name: Print Secret

on: [push]

jobs:
  deploy:
    name: Print Secret
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Unlock secrets
        uses: sliteteam/github-action-git-crypt-unlock@1.2.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
      - run: cat development.secret
      - run: rm development.secret
